name = "advent-of-code"
version = "0.1.0"
defaultTargets = ["advent-of-code"]

[[require]]
name = "batteries"
git = "https://github.com/leanprover-community/batteries"
rev = "v4.27.0"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.27.0"

[[lean_lib]]
name = "AdventOfCode"

[[lean_exe]]
name = "advent-of-code"
root = "Main"
